// Code generated by goyacc -p starlark -o starlark_parser.go starlark_parser.y. DO NOT EDIT.

//line starlark_parser.y:2
package starlark

import __yyfmt__ "fmt"

//line starlark_parser.y:2

import (
	"fmt"
)

//line starlark_parser.y:11
type starlarkSymType struct {
	yys   int
	token *tokenWithLexer
	node  string

	argument   ArgumentNode
	arguments  []ArgumentNode
	reportFile *ReportFile

	loadNode    *ReportFile_Import
	exportNode  *ReportFile_Export
	fnNode      *ReportFile_Function
	commentNode *ReportFile_Comment
	returnNode  *ReportFile_Return
}

const commentInline = 57346
const commentMultiline = 57347
const ident = 57348
const boolLiteral = 57349
const integerLiteral = 57350
const floatLiteral = 57351
const stringLiteral = 57352
const defKeyword = 57353
const loadKeyword = 57354
const returnKeyword = 57355
const moduleKeyword = 57356

var starlarkToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"commentInline",
	"commentMultiline",
	"ident",
	"boolLiteral",
	"integerLiteral",
	"floatLiteral",
	"stringLiteral",
	"defKeyword",
	"loadKeyword",
	"returnKeyword",
	"moduleKeyword",
	"'.'",
	"','",
	"':'",
	"'('",
	"')'",
	"'['",
	"']'",
	"'{'",
	"'}'",
	"'='",
	"'*'",
}

var starlarkStatenames = [...]string{}

const starlarkEofCode = 1
const starlarkErrCode = 2
const starlarkInitialStackSize = 16

//line yacctab:1
var starlarkExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const starlarkPrivate = 57344

const starlarkLast = 34

var starlarkAct = [...]int{
	9, 10, 15, 26, 31, 22, 19, 11, 13, 12,
	14, 21, 27, 27, 16, 17, 28, 28, 32, 24,
	18, 23, 20, 8, 1, 29, 5, 4, 7, 30,
	25, 2, 6, 3,
}

var starlarkPact = [...]int{
	-1000, -1000, -4, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 16, -1000, -7, -13, -1000, -1000, -1000, -1000, -1000,
	-1000, 11, 9, 7, -1000, 6, -1000, -20, -1000, -1000,
	-1000, 8, -1000,
}

var starlarkPgo = [...]int{
	0, 33, 32, 31, 3, 30, 28, 27, 26, 24,
	23,
}

var starlarkR1 = [...]int{
	0, 9, 3, 3, 3, 3, 3, 3, 3, 1,
	1, 2, 4, 4, 5, 5, 6, 7, 8, 10,
	10, 10, 10, 10,
}

var starlarkR2 = [...]int{
	0, 1, 0, 2, 2, 2, 2, 2, 2, 1,
	1, 5, 3, 1, 1, 2, 3, 2, 1, 1,
	1, 1, 1, 1,
}

var starlarkChk = [...]int{
	-1000, -9, -3, -1, -7, -8, -2, -6, -10, 4,
	5, 11, 13, 12, 14, 6, 18, 19, 24, 10,
	6, 18, 18, 10, 10, -5, -4, 6, 10, 19,
	-4, 24, 10,
}

var starlarkDef = [...]int{
	2, -2, 1, 3, 4, 5, 6, 7, 8, 9,
	10, 0, 18, 0, 0, 19, 20, 21, 22, 23,
	17, 0, 0, 0, 16, 0, 14, 0, 13, 11,
	15, 0, 12,
}

var starlarkTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	18, 19, 25, 3, 16, 3, 15, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 17, 3,
	3, 24, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 20, 3, 21, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 22, 3, 23,
}

var starlarkTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14,
}

var starlarkTok3 = [...]int{
	0,
}

var starlarkErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	starlarkDebug        = 0
	starlarkErrorVerbose = false
)

type starlarkLexer interface {
	Lex(lval *starlarkSymType) int
	Error(s string)
}

type starlarkParser interface {
	Parse(starlarkLexer) int
	Lookahead() int
}

type starlarkParserImpl struct {
	lval  starlarkSymType
	stack [starlarkInitialStackSize]starlarkSymType
	char  int
}

func (p *starlarkParserImpl) Lookahead() int {
	return p.char
}

func starlarkNewParser() starlarkParser {
	return &starlarkParserImpl{}
}

const starlarkFlag = -1000

func starlarkTokname(c int) string {
	if c >= 1 && c-1 < len(starlarkToknames) {
		if starlarkToknames[c-1] != "" {
			return starlarkToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func starlarkStatname(s int) string {
	if s >= 0 && s < len(starlarkStatenames) {
		if starlarkStatenames[s] != "" {
			return starlarkStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func starlarkErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !starlarkErrorVerbose {
		return "syntax error"
	}

	for _, e := range starlarkErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + starlarkTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := starlarkPact[state]
	for tok := TOKSTART; tok-1 < len(starlarkToknames); tok++ {
		if n := base + tok; n >= 0 && n < starlarkLast && starlarkChk[starlarkAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if starlarkDef[state] == -2 {
		i := 0
		for starlarkExca[i] != -1 || starlarkExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; starlarkExca[i] >= 0; i += 2 {
			tok := starlarkExca[i]
			if tok < TOKSTART || starlarkExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if starlarkExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += starlarkTokname(tok)
	}
	return res
}

func starlarklex1(lex starlarkLexer, lval *starlarkSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = starlarkTok1[0]
		goto out
	}
	if char < len(starlarkTok1) {
		token = starlarkTok1[char]
		goto out
	}
	if char >= starlarkPrivate {
		if char < starlarkPrivate+len(starlarkTok2) {
			token = starlarkTok2[char-starlarkPrivate]
			goto out
		}
	}
	for i := 0; i < len(starlarkTok3); i += 2 {
		token = starlarkTok3[i+0]
		if token == char {
			token = starlarkTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = starlarkTok2[1] /* unknown char */
	}
	if starlarkDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", starlarkTokname(token), uint(char))
	}
	return char, token
}

func starlarkParse(starlarklex starlarkLexer) int {
	return starlarkNewParser().Parse(starlarklex)
}

func (starlarkrcvr *starlarkParserImpl) Parse(starlarklex starlarkLexer) int {
	var starlarkn int
	var starlarkVAL starlarkSymType
	var starlarkDollar []starlarkSymType
	_ = starlarkDollar // silence set and not used
	starlarkS := starlarkrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	starlarkstate := 0
	starlarkrcvr.char = -1
	starlarktoken := -1 // starlarkrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		starlarkstate = -1
		starlarkrcvr.char = -1
		starlarktoken = -1
	}()
	starlarkp := -1
	goto starlarkstack

ret0:
	return 0

ret1:
	return 1

starlarkstack:
	/* put a state and value onto the stack */
	if starlarkDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", starlarkTokname(starlarktoken), starlarkStatname(starlarkstate))
	}

	starlarkp++
	if starlarkp >= len(starlarkS) {
		nyys := make([]starlarkSymType, len(starlarkS)*2)
		copy(nyys, starlarkS)
		starlarkS = nyys
	}
	starlarkS[starlarkp] = starlarkVAL
	starlarkS[starlarkp].yys = starlarkstate

starlarknewstate:
	starlarkn = starlarkPact[starlarkstate]
	if starlarkn <= starlarkFlag {
		goto starlarkdefault /* simple state */
	}
	if starlarkrcvr.char < 0 {
		starlarkrcvr.char, starlarktoken = starlarklex1(starlarklex, &starlarkrcvr.lval)
	}
	starlarkn += starlarktoken
	if starlarkn < 0 || starlarkn >= starlarkLast {
		goto starlarkdefault
	}
	starlarkn = starlarkAct[starlarkn]
	if starlarkChk[starlarkn] == starlarktoken { /* valid shift */
		starlarkrcvr.char = -1
		starlarktoken = -1
		starlarkVAL = starlarkrcvr.lval
		starlarkstate = starlarkn
		if Errflag > 0 {
			Errflag--
		}
		goto starlarkstack
	}

starlarkdefault:
	/* default state action */
	starlarkn = starlarkDef[starlarkstate]
	if starlarkn == -2 {
		if starlarkrcvr.char < 0 {
			starlarkrcvr.char, starlarktoken = starlarklex1(starlarklex, &starlarkrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if starlarkExca[xi+0] == -1 && starlarkExca[xi+1] == starlarkstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			starlarkn = starlarkExca[xi+0]
			if starlarkn < 0 || starlarkn == starlarktoken {
				break
			}
		}
		starlarkn = starlarkExca[xi+1]
		if starlarkn < 0 {
			goto ret0
		}
	}
	if starlarkn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			starlarklex.Error(starlarkErrorMessage(starlarkstate, starlarktoken))
			Nerrs++
			if starlarkDebug >= 1 {
				__yyfmt__.Printf("%s", starlarkStatname(starlarkstate))
				__yyfmt__.Printf(" saw %s\n", starlarkTokname(starlarktoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for starlarkp >= 0 {
				starlarkn = starlarkPact[starlarkS[starlarkp].yys] + starlarkErrCode
				if starlarkn >= 0 && starlarkn < starlarkLast {
					starlarkstate = starlarkAct[starlarkn] /* simulate a shift of "error" */
					if starlarkChk[starlarkstate] == starlarkErrCode {
						goto starlarkstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if starlarkDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", starlarkS[starlarkp].yys)
				}
				starlarkp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if starlarkDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", starlarkTokname(starlarktoken))
			}
			if starlarktoken == starlarkEofCode {
				goto ret1
			}
			starlarkrcvr.char = -1
			starlarktoken = -1
			goto starlarknewstate /* try again in the same state */
		}
	}

	/* reduction by production starlarkn */
	if starlarkDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", starlarkn, starlarkStatname(starlarkstate))
	}

	starlarknt := starlarkn
	starlarkpt := starlarkp
	_ = starlarkpt // guard against "declared and not used"

	starlarkp -= starlarkR2[starlarkn]
	// starlarkp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if starlarkp+1 >= len(starlarkS) {
		nyys := make([]starlarkSymType, len(starlarkS)*2)
		copy(nyys, starlarkS)
		starlarkS = nyys
	}
	starlarkVAL = starlarkS[starlarkp+1]

	/* consult goto table to find next state */
	starlarkn = starlarkR1[starlarkn]
	starlarkg := starlarkPgo[starlarkn]
	starlarkj := starlarkg + starlarkS[starlarkp].yys + 1

	if starlarkj >= starlarkLast {
		starlarkstate = starlarkAct[starlarkg]
	} else {
		starlarkstate = starlarkAct[starlarkj]
		if starlarkChk[starlarkstate] != -starlarkn {
			starlarkstate = starlarkAct[starlarkg]
		}
	}
	// dummy call; replaced with literal code
	switch starlarknt {

	case 1:
		starlarkDollar = starlarkS[starlarkpt-1 : starlarkpt+1]
//line starlark_parser.y:46
		{
			starlarklex.(reporter).SetReport(starlarkDollar[1].reportFile)
		}
	case 2:
		starlarkDollar = starlarkS[starlarkpt-0 : starlarkpt+1]
//line starlark_parser.y:50
		{
			starlarkVAL.reportFile = &ReportFile{}
		}
	case 3:
		starlarkDollar = starlarkS[starlarkpt-2 : starlarkpt+1]
//line starlark_parser.y:54
		{
			fmt.Println("Comment:", starlarkDollar[2].commentNode)
			starlarkVAL.reportFile.Comments = append(starlarkVAL.reportFile.Comments, starlarkDollar[2].commentNode)
		}
	case 4:
		starlarkDollar = starlarkS[starlarkpt-2 : starlarkpt+1]
//line starlark_parser.y:59
		{
			fmt.Println("DefStmt:", starlarkDollar[2].fnNode)
			starlarkVAL.reportFile.Functions = append(starlarkVAL.reportFile.Functions, starlarkDollar[2].fnNode)
		}
	case 5:
		starlarkDollar = starlarkS[starlarkpt-2 : starlarkpt+1]
//line starlark_parser.y:64
		{
			// fmt.Println("ReturnStmt")
			starlarkVAL.reportFile.Returns = append(starlarkVAL.reportFile.Returns, starlarkDollar[2].returnNode)
		}
	case 6:
		starlarkDollar = starlarkS[starlarkpt-2 : starlarkpt+1]
//line starlark_parser.y:69
		{
			fmt.Println("LoadStmt:", starlarkDollar[2].loadNode)
			starlarkVAL.reportFile.Imports = append(starlarkVAL.reportFile.Imports, starlarkDollar[2].loadNode)
		}
	case 7:
		starlarkDollar = starlarkS[starlarkpt-2 : starlarkpt+1]
//line starlark_parser.y:74
		{
			fmt.Println("ModuleStmt:", starlarkDollar[2].exportNode)
			starlarkVAL.reportFile.Exports = append(starlarkVAL.reportFile.Exports, starlarkDollar[2].exportNode)
		}
	case 9:
		starlarkDollar = starlarkS[starlarkpt-1 : starlarkpt+1]
//line starlark_parser.y:82
		{
			starlarkVAL.commentNode = &ReportFile_Comment{
				Value: starlarkDollar[1].token.String(),
				Pos:   starlarkDollar[1].token.Pos(),
			}
		}
	case 10:
		starlarkDollar = starlarkS[starlarkpt-1 : starlarkpt+1]
//line starlark_parser.y:87
		{
			starlarkVAL.commentNode = &ReportFile_Comment{
				Value:     starlarkDollar[1].token.String(),
				MultiLine: true,
				Pos:       starlarkDollar[1].token.Pos(),
			}
		}
	case 11:
		starlarkDollar = starlarkS[starlarkpt-5 : starlarkpt+1]
//line starlark_parser.y:97
		{
			starlarkVAL.loadNode = &ReportFile_Import{Name: starlarkDollar[3].token.String(), Args: starlarkDollar[4].arguments, Pos: starlarkDollar[1].token.Pos()}
		}
	case 12:
		starlarkDollar = starlarkS[starlarkpt-3 : starlarkpt+1]
//line starlark_parser.y:102
		{
			starlarkVAL.argument = ArgumentNode{
				ArgumentNode_Value{Ident: starlarkDollar[1].token.String()},
				ArgumentNode_Value{StringLiteral: starlarkDollar[3].token.String()},
			}
		}
	case 13:
		starlarkDollar = starlarkS[starlarkpt-1 : starlarkpt+1]
//line starlark_parser.y:108
		{
			starlarkVAL.argument = ArgumentNode{
				ArgumentNode_Value{StringLiteral: starlarkDollar[1].token.String()},
			}
		}
	case 14:
		starlarkDollar = starlarkS[starlarkpt-1 : starlarkpt+1]
//line starlark_parser.y:113
		{
			starlarkVAL.arguments = []ArgumentNode{starlarkDollar[1].argument}
		}
	case 15:
		starlarkDollar = starlarkS[starlarkpt-2 : starlarkpt+1]
//line starlark_parser.y:115
		{
			starlarkVAL.arguments = append(starlarkDollar[1].arguments, starlarkDollar[2].argument)
		}
	case 16:
		starlarkDollar = starlarkS[starlarkpt-3 : starlarkpt+1]
//line starlark_parser.y:120
		{
			starlarkVAL.exportNode = &ReportFile_Export{Name: starlarkDollar[3].token.String(), Pos: starlarkDollar[1].token.Pos()}
		}
	case 17:
		starlarkDollar = starlarkS[starlarkpt-2 : starlarkpt+1]
//line starlark_parser.y:125
		{
			starlarkVAL.fnNode = &ReportFile_Function{Name: starlarkDollar[2].token.String(), Pos: starlarkDollar[1].token.Pos()}
		}
	case 18:
		starlarkDollar = starlarkS[starlarkpt-1 : starlarkpt+1]
//line starlark_parser.y:130
		{
			starlarkVAL.returnNode = &ReportFile_Return{Pos: starlarkDollar[1].token.Pos()}
		}
	}
	goto starlarkstack /* stack new state and value */
}
